[providers]
providers = ["php", "node"]

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.bcmath", "nodejs_20"]

[phases.build]
cmds = ["npm ci || npm install", "npm run build"]
